# Page settings

baseURL = "http://example.org/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = ""
    description = ""


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"


    [params.profile]
        enable = true
        name = "Lior DILER"
        tagline = "Full Stack Developer"
        avatar = "profile2.png"

    [params.summary]
        enable = true
        #text = "From my passion, professionnal experience and studiesAcross my professionnal experiences and thanks to my 5 years of #programming school, I have found how to unite passion, work and studies. I desire to work in programming."
        text = "My 5 years of studying and professional experience has allowed programming to become my passion."
        textSecond = "With a wide variety of experience in different fields such as Frontend, Backend and Video Game Development, I have aquired the skill to adapt and learn new technologies."
    [params.contact]
        enable = true
        location = "Paris - France"

        [[params.contact.list]]
        style = "fas"
        icon = "fa-phone-square"
        url = "tel:#"
        text = "+33 6 48 23 58 60"
        [[params.contact.list]]
        style = "fas"
        icon = "fa-envelope-square"
        url = "mailto:#"
        text = "diler.lior@gmail.com"

    [params.skills]
        enable = true

    [[params.skills.list]]
    title = ""

    [[params.skills.list.items]]
    details = "Self-motivated"
    [[params.skills.list.items]]
    details = "Curious"
    [[params.skills.list.items]]
    details = "Serious"
    [[params.skills.list.items]]
    details = "Passionate"



    [params.education]
        enable = true
	[[params.education.list]]
        degree = "Master's degree in software and network project management"
        university = "ESGI Paris"
        dates = "2020 - 2022"
	[[params.education.list]]
        degree = "Bachelor's degree in software and network project management"
        university = "ESGI Paris"
        dates = "2019 - 2020"
    [[params.education.list]]
        degree = "Advanced technician's diploma in IT"
        university = "CFA Insta"
        dates = "2017 - 2019"
	[[params.education.list]]
        degree = "High school diploma in Laboratory Sciences"
        university = "Ecole Technique Supérieur du Laboratoire"
        dates = "2016 - 2017"
	

    [params.languages]
        enable = true

    [[params.languages.list]]
        name = "French"
        level = "Native language"
    [[params.languages.list]]
        name = "English"
        level = "Native language"
	[[params.languages.list]]
        name = "Turkish"
        level = "Fluent"



    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Music"
        [[params.interests.list]]
        name = "Travelling"
        [[params.interests.list]]
        name = "Video game competitions"

    #[params.status]
     #   enable = true
      #  [[params.status.list]]
       # name = "Recognized as a handicapped worker"


    [params.projects]
        enable = true
	[[params.projects.list]]
		#TODO: add a technical experience field like in professional projects
        title = "Participation at the SIGGRAPH conference"
        details = "Technical Environnement: C# , C++, Python, Unity, Jupiter-notebook, Tensorflow, GGPO"
        context = "Creation of an open source library called Rollback Hybrid Netcode to improve upon the current most successful multiplayer connection method for videogames."
        dates = "October 2021 - Now"
        	[[params.projects.list.items]]
                    details = "Conception of the non opinionated architecture of the library, giving developers endpoints to modify its behavior."
            [[params.projects.list.items]]
                    details = "Implemented different approaches to let the developer choose if it is more accessible or performant"
            [[params.projects.list.items]]
                    details = "creation of a custom modulable C++ machine learning library"
            [[params.projects.list.items]]
                    details = "creation of an AI that predicts player inputs during an online game"
            [[params.projects.list.items]]
                    details = "creating and analysing datasets on Open Sources games to train the AI"
            [[params.projects.list.items]]
                    details = "Creation of a library to improve online network for videogames using GGPO so that they easily implement our solution"

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Full Stack Developer"
        dates = "October 2019 - August 2022"
        company = "Inria"
        details = "Technical Environment: Linux, Docker, Node.js, React, MongoDB, Gitlab-ci, Nginx"
            [[params.experience.list.items]]
            details = "In charge of the modelisation and creation of a Research and Development project called Universal Social Network Bus from scratch."
            [[params.experience.list.items]]
            details = "Designed the structure of a multi social media messaging system"
            [[params.experience.list.items]]
            details = "Implemented the website, messaging across social medias and database management"
            [[params.experience.list.items]]
            details = "Automated unit testing and deployment from staging to production"
            [[params.experience.list.items]]
            details = "Technology and design choices"
            [[params.experience.list.items]]
            details = "autonomous, deadlines"
            [[params.experience.list.items]]
            details = "Wrote and automated documentation generation"
        
        [[params.experience.list]]
        title = "R&D Developer in Robotics"
        dates = "June 2017 - August 2019"
        company = "Teamnet"
        details = "Technical Environment: Java Spring, Linux, MYSQL, Git, Jenkins, SonarQube"
        [[params.experience.list.items]]
        details = "Creation of a linguistic Chatbot"
        [[params.experience.list.items]]
        details = "Development of the backend (API REST, program, database...)"
        [[params.experience.list.items]]
        details = "Setting up Docker"
		[[params.experience.list.items]]
		details = "Work in scrum orga"
		[[params.experience.list.items]]
		details = "Worked with a linguiste to conceive a Chatbot for robots aimed to help elderly people"
		[[params.experience.list.items]]
        details = "Verified the code quality with sonarCube and made it release stable with jenkins"
        [[params.experience.list.items]]
        details = "Research, benchmarking and developpement on robot features"


    [params.information]
        enable = true

	[[params.information.list]]
        title = ""
        [[params.information.list.items]]
        details = "Languages: C#, C++, C, Java, Javascript, Python, Kotlin"
        hidden = ", Spring, Machine learning, Deep learning"
        [[params.information.list.items]]
        details = "Database: MySQL, MongoDB"
        hidden = ", Artificial Intelligence, Algorithm"
	    [[params.information.list.items]]
        details = "Frameworks : Node.js, React, Nginx"
        [[params.information.list.items]]
        details = "Tools: Docker, Git, JetBrains, Visual Studio"


	#[[params.information.list]]
        #title = "Participation à la gestion de projets informatiques en alternance chez RTE"
	#details = "Septembre 2017 - août 2019"

	#[[params.information.list.items]]
        #details = "En contrat d'alternance pour 2 ans en vue d'un BTS SIO (Services Informatiques aux Organisations) au sein du pôle 'Système d'information des Achats' de RTE."
	#[[params.information.list.items]]
	#details = "Référente GCP module SAP et valideuse achat pour le référentiel fournisseur de RTE."
	#[[params.information.list.items]]
	#details = "Gestion des évolutions GCP selon les besoins utilisateurs."
	#[[params.information.list.items]]
	#details = "Administratrice des outils du SI achats de la Direction des achats et en charge des habilitations sur les différentes applications."
	#[[params.information.list.items]]
	#details = "Automatisation de processus grâce à Visual Basic. Mise en place de documentation utilisateur."



    [params.social]
        enable = true

    [[params.social.list]]
        style = "fab"
        icon = "fa-github-square"
        url = "https://github.com/Neffros"
	    title = "Github - Neffros"
    [[params.social.list]]
        style = "fab"
        icon = "fa-linkedin"
        url = "https://www.linkedin.com/in/lior-diler-b32b7a149/"
        title = "Linkedin - Lior DILER"
	





