# Page settings

baseURL = "http://example.org/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = ""
    description = ""


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"


    [params.profile]
        enable = true
        name = "Lior DILER"
        tagline = "Full Stack Developer"
        avatar = "profile2.png"

    [params.summary]
        enable = true
        #text = "From my passion, professionnal experience and studiesAcross my professionnal experiences and thanks to my 5 years of #programming school, I have found how to unite passion, work and studies. I desire to work in programming."
        text = "My 5 years of studying and professional experience has allowed programming to become my passion."
        textSecond = "With a wide variety of experience in different fields such as Frontend, Backend and Video Game Development, I have aquired the skill to adapt and learn new technologies."
    [params.contact]
        enable = true
        location = "Paris - France"

        [[params.contact.list]]
        style = "fas"
        icon = "fa-phone-square"
        url = "tel:#"
        text = "+33 6 48 23 58 60"
        [[params.contact.list]]
        style = "fas"
        icon = "fa-envelope-square"
        url = "mailto:#"
        text = "diler.lior@gmail.com"

    [params.skills]
        enable = true

    [[params.skills.list]]
    title = ""

    [[params.skills.list.items]]
    details = "Self-motivated"
    [[params.skills.list.items]]
    details = "Curious"
    [[params.skills.list.items]]
    details = "Serious"
    [[params.skills.list.items]]
    details = "Passionate"



    [params.education]
        enable = true
	[[params.education.list]]
        degree = "Master's degree in software and network project management"
        university = "ESGI Paris"
        dates = "2020 - 2022"
	[[params.education.list]]
        degree = "Bachelor's degree in software and network project management"
        university = "ESGI Paris"
        dates = "2019 - 2020"
    [[params.education.list]]
        degree = "Advanced technician's diploma in IT"
        university = "CFA Insta"
        dates = "2017 - 2019"
	[[params.education.list]]
        degree = "High school diploma in Laboratory Sciences"
        university = "Ecole Technique Supérieur du Laboratoire"
        dates = "2016 - 2017"
	

    [params.languages]
        enable = true

    [[params.languages.list]]
        name = "French"
        level = "Native language"
    [[params.languages.list]]
        name = "English"
        level = "Native language"
	[[params.languages.list]]
        name = "Turkish"
        level = "Fluent"



    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Music"
        [[params.interests.list]]
        name = "Travelling"
        [[params.interests.list]]
        name = "Video game competitions"

    #[params.status]
     #   enable = true
      #  [[params.status.list]]
       # name = "Recognized as a handicapped worker"


    [params.projects]
        enable = true
	[[params.projects.list]]
		#TODO: add a technical experience field like in professional projects
        title = "Participation at the SIGGRAPH conference"
        details = "Technical Environnement: C# , C++, Python, Unity, Jupiter-notebook, Tensorflow, GGPO"
        context = "Creation and presentation of an open source library called Rollback Hybrid Netcode at the SIGGRAPH research convention. Designed to improve upon the current most successful multiplayer connection method for videogames."
        dates = "October 2021 - Now"
        	[[params.projects.list.items]]
                    details = "Conceptualized a non opinionated architecture for the library, giving developers endpoints to modify its behavior"
            [[params.projects.list.items]]
                    details = "Implemented different approaches to let the developer choose if it is more accessible or performant"
            [[params.projects.list.items]]
                    details = "Developed a custom modulable C++ machine learning library"
            [[params.projects.list.items]]
                    details = "Created an AI that predicts player inputs during an online game"
            [[params.projects.list.items]]
                    details = "Made and analysed datasets on Open Source games to train the machine learning models"
            [[params.projects.list.items]]
                    details = "Built the library on top of the most popular online network library for videogames (GGPO) so that developers can easily replace it with our solution"

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "R&D Full Stack Developer"
        dates = "October 2019 - August 2022"
        company = "Inria"
        context = "Creation in autonomy of a network platform called Socialbus, letting users communicate in chat groups using their favorite messaging application."
        details = "Technical Environment: Linux, Docker, Node.js, React, MongoDB, Gitlab-ci, Nginx"
            [[params.experience.list.items]]
            details = "Made a proof of concept of Socialbus before producing the final application"
			[[params.experience.list.items]]
			details = "Designed the project architecture and choosing the technologies based on the needs"
            [[params.experience.list.items]]
            details = "Modelized the Multi social media messaging system from scratch"
            [[params.experience.list.items]]
            details = "Developed the REST API for the network platform in Node.js"
            [[params.experience.list.items]]
            details = "Implemented the React website for users to create, join and manage groups"
            [[params.experience.list.items]]
            details = "Set up unit testing automatization and CI/CD with versionning for deployment from staging to production"
            [[params.experience.list.items]]
            details = "Dockerized the project and deploying with Dockerhub"
			[[params.experience.list.items]]
			details = "Written documentation and automating its deployment"
            [[params.experience.list.items]]
            details = "Respected long term and short term deadlines"

        [[params.experience.list]]
        title = "R&D Developer in Robotics"
        dates = "June 2017 - August 2019"
        company = "Teamnet"
        context = "Development in an Agile team of a linguistic Chatbot, conceived to interact and help elderly people. It will then be implemented in physical robots."
        details = "Technical Environment: Linux, Java Spring, Python, MYSQL, Git, Jenkins, SonarQube"
        [[params.experience.list.items]]
        details = "Researched, benchmarked and developed on robot features (Chatbot, voice origin detection to face the human talking, intruder detection)"
        [[params.experience.list.items]]
        details = "Developed a REST API to interact with the linguistic chatbot"
        [[params.experience.list.items]]
        details = "Implemented the language algorithmes used by the chatbot in Java"
		[[params.experience.list.items]]
		details = "Worked in scrum organization with a professional linguist to make the chatbot's sentences realistic"
		[[params.experience.list.items]]
        details = "Verified the code quality with SonarCube and made released it with Jenkins and Docker"



    [params.information]
        enable = true

	[[params.information.list]]
        title = ""
        [[params.information.list.items]]
        details = "Languages: C#, C++, C, Java, Javascript, Python, Kotlin"
        hidden = ", Spring, Machine learning, Deep learning"
        [[params.information.list.items]]
        details = "Database: MySQL, MongoDB"
        hidden = ", Artificial Intelligence, Algorithm"
	    [[params.information.list.items]]
        details = "Frameworks : Node.js, React, Nginx"
        [[params.information.list.items]]
        details = "Tools: Docker, Git, JetBrains, Visual Studio"


	#[[params.information.list]]
        #title = "Participation à la gestion de projets informatiques en alternance chez RTE"
	#details = "Septembre 2017 - août 2019"

	#[[params.information.list.items]]
        #details = "En contrat d'alternance pour 2 ans en vue d'un BTS SIO (Services Informatiques aux Organisations) au sein du pôle 'Système d'information des Achats' de RTE."
	#[[params.information.list.items]]
	#details = "Référente GCP module SAP et valideuse achat pour le référentiel fournisseur de RTE."
	#[[params.information.list.items]]
	#details = "Gestion des évolutions GCP selon les besoins utilisateurs."
	#[[params.information.list.items]]
	#details = "Administratrice des outils du SI achats de la Direction des achats et en charge des habilitations sur les différentes applications."
	#[[params.information.list.items]]
	#details = "Automatisation de processus grâce à Visual Basic. Mise en place de documentation utilisateur."



    [params.social]
        enable = true

    [[params.social.list]]
        style = "fab"
        icon = "fa-github-square"
        url = "https://github.com/Neffros"
	    title = "Github - Neffros"
    [[params.social.list]]
        style = "fab"
        icon = "fa-linkedin"
        url = "https://www.linkedin.com/in/lior-diler-b32b7a149/"
        title = "Linkedin - Lior DILER"
	





