# Page settings

baseURL = "http://example.org/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = ""
    description = ""


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"


    [params.profile]
        enable = true
        name = "Lior DILER"
        tagline = "Full Stack Developer"
        avatar = "profile2.png"

    [params.summary]
        enable = true
        #text = "From my passion, professionnal experience and studiesAcross my professionnal experiences and thanks to my 5 years of #programming school, I have found how to unite passion, work and studies. I desire to work in programming."
        text = "[sentence or two that says that i have xp and i'm passionate and willing to learn even languages i don't master yet]"
    [params.contact]
        enable = true
        location = "Paris - France"

        [[params.contact.list]]
        style = "fas"
        icon = "fa-phone-square"
        url = "tel:#"
        text = "+33 6 48 23 58 60"
        [[params.contact.list]]
        style = "fas"
        icon = "fa-envelope-square"
        url = "mailto:#"
        text = "diler.lior@gmail.com"

    [params.skills]
        enable = true

    [[params.skills.list]]
    title = ""

    [[params.skills.list.items]]
    details = "Self-motivated"
    [[params.skills.list.items]]
    details = "Curious"
    [[params.skills.list.items]]
    details = "Serious"
    [[params.skills.list.items]]
    details = "Passionate"



    [params.education]
        enable = true
	[[params.education.list]]
        degree = "Master's degree in software and network project management"
        university = "ESGI Paris"
        dates = "2020 - 2022"
	[[params.education.list]]
        degree = "Bachelor's degree in software and network project management"
        university = "ESGI Paris"
        dates = "2019 - 2020"
    [[params.education.list]]
        degree = "Advanced technician's diploma in IT"
        university = "CFA Insta"
        dates = "2017 - 2019"
	[[params.education.list]]
        degree = "High school diploma in Laboratory Sciences"
        university = "Lycée Ecole Technique Supérieur du Laboratoire"
        dates = "2016 - 2017"
	

    [params.languages]
        enable = true

    [[params.languages.list]]
        name = "French"
        level = "Native language"
    [[params.languages.list]]
        name = "English"
        level = "Native language"
	[[params.languages.list]]
        name = "Turkish"
        level = "Fluent"



    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Music"
        [[params.interests.list]]
        name = "Travelling"
        [[params.interests.list]]
        name = "Video game competitions"

    #[params.status]
     #   enable = true
      #  [[params.status.list]]
       # name = "Recognized as a handicapped worker"


    [params.projects]
        enable = true
	[[params.projects.list]]
        title = "Contribution to the SIGGRAPH research competition, Rollback Hybrid Netcode (C++, C#)"
	    #tagline = "Invention du Rollback Hybrid Netcode, une amélioration pour les jeux en lignes avec une IA de machine learning. "

	[[params.projects.list]]
        title = "Creation of courses on immersion in Virtual Reality with Binaural Audio (C#, C)"
	    #tagline = "Support écrit et vidéo ainsi qu'implémentation de projets en réalité virtuelle."

	[[params.projects.list]]
        title = "Implementation of a Machine Learning Library  (C++)"
        #tagline = "TODO"
	[[params.projects.list]]
        title = "Genetic Algorithm for Procedural Animation (C#, Python, Unity, Blender)"
        #tagline = "TODO"

	[[params.projects.list]]
        title = "Artificial Intelligence for Video Games (C#, C++)"
        #tagline = "TODO"

	[[params.projects.list]]
        title = "Image Processing Applications (C++, openCV)"
	    #tagline ="TODO"

    [[params.projects.list]]
        title = "Ray-tracing Engine (C++)"
        #tagline = "TODO"

    [[params.projects.list]]
        title = "2D Game Engine (C++)"

	[[params.projects.list]]
        title = "Compute Shader for Particle Generation (C#, Shader)"

    [[params.projects.list]]
        title = "Development of a Real-time Strategy Game (C#, Unity)"

    [[params.projects.list]]
        title = "Development of a Pathfinding Game (C++, Unreal Engine)"

    [[params.projects.list]]
        title = "Generation of Bézier Curves (C#, Unity)"

    [[params.projects.list]]
        title = "Procedural Rendering (WebGL, Blender)"

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Full Stack Developer"
        dates = "October 2019 - August 2022"
        company = "Inria"
        details = "Technical Environment: Linux, Docker, NodeJS, React, MongoDB, Gitlab-ci, Nginx"

            [[params.experience.list.items]]
            details = "Software architecture design"
            [[params.experience.list.items]]
            details = "Application development (backend and frontend)"
            [[params.experience.list.items]]
            details = "Unit testing"
            [[params.experience.list.items]]
            details = "Automatic deployment"
            [[params.experience.list.items]]
            details = "Application security management"
            [[params.experience.list.items]]
            details = "Automatic documentation generation"
        
        [[params.experience.list]]
        title = "R&D Developer in Robotics"
        dates = "June 2017 - August 2019"
        company = "Teamnet"
        details = "Technical Environment: Java Spring, Linux, MYSQL, Git, Jenkins, Sonar"
        [[params.experience.list.items]]
        details = "Creation of a linguistic Chatbot"
        [[params.experience.list.items]]
        details = "Development of the backend (API, program, database...)"
        [[params.experience.list.items]]
        details = "Setting up Docker"
        [[params.experience.list.items]]
        details = "Database management"


    [params.information]
        enable = true
        [[params.information.list]]

	[[params.information.list]]
        title = ""
        [[params.information.list.items]]
        details = "Languages: C#, C++, C, Java, Javascript, Python, Android"
        [[params.information.list.items]]
        details = "Database: SQL, MongoDB"
        [[params.information.list.items]]
        details = "Systems: Linux, Windows, Android, MacOS"
	    [[params.information.list.items]]
        details = "Frameworks : Node.js, React, Express, Nginx, OpenGL, Shader"
        [[params.information.list.items]]
        details = "Tools: Docker, Github, Gitlab, Unity, Unreal Engine, Blender, Houdini"


	#[[params.information.list]]
        #title = "Participation à la gestion de projets informatiques en alternance chez RTE"
	#details = "Septembre 2017 - août 2019"

	#[[params.information.list.items]]
        #details = "En contrat d'alternance pour 2 ans en vue d'un BTS SIO (Services Informatiques aux Organisations) au sein du pôle 'Système d'information des Achats' de RTE."
	#[[params.information.list.items]]
	#details = "Référente GCP module SAP et valideuse achat pour le référentiel fournisseur de RTE."
	#[[params.information.list.items]]
	#details = "Gestion des évolutions GCP selon les besoins utilisateurs."
	#[[params.information.list.items]]
	#details = "Administratrice des outils du SI achats de la Direction des achats et en charge des habilitations sur les différentes applications."
	#[[params.information.list.items]]
	#details = "Automatisation de processus grâce à Visual Basic. Mise en place de documentation utilisateur."



    [params.social]
        enable = true

    [[params.social.list]]
        style = "fab"
        icon = "fa-github-square"
        url = "https://github.com/Neffros"
	    title = "Github - Neffros"
    [[params.social.list]]
        style = "fab"
        icon = "fa-linkedin"
        url = "https://www.linkedin.com/in/lior-diler-b32b7a149/"
        title = "Linkedin - Lior DILER"
	





